### ISSUE TITLE
Linking to numpy means lots of big conda binaries

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmb_data#10]
Since `_muller.pyx` uses the numpy c api, we need to make a conda package for each numpy version outer product each python version. This seems wasteful. The 300 MB of data doesn't change with either python or numpy.

Might be worth considering having just data (and seeing if conda packages can be released with no python dependence) and keeping all the code in msmbuilder

**Comment by cxhernandez** [comment]
One argument for keeping it is that if I have zero desire to use MSMBuilder but want access to all the testing data for my own project, I could use just this repo. But yeah, otherwise it does seem kind of extraneous....
