### ISSUE TITLE
Actually remove dependencies

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmb_data#9]
The package doesn't import without sklearn and msmbuilder. The functionality we import from there is really minimal. Can we re-write to remove this dependency

**Comment by mpharrigan** [comment]
sklearn `check_random_state` just seeds a numpy RandomState instance

**Comment by mpharrigan** [comment]
`verboseload` and `verbosedump` are just pickle functions and a print statement

**Comment by mpharrigan** [comment]
`_solve_msm_eigensystem` is 6 lines that it wouldn't hurt to just copy into this project

**Comment by cxhernandez** [comment]
done in #11
